spring:
  application:
    name: template_rest_api
  datasource:
    url: '${POSTGRES_URI}'
    username: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: youtube-api

module-name: youtube
api-version: 3.0